"""add version column for optimistic locking

Revision ID: 9621b3f1a976
Revises: af2bf91f47dd
Create Date: 2026-08-18 22:37:26.884475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9621b3f1a976'
down_revision: Union[str, Sequence[str], None] = 'af2bf91f47dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_sessions', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_sessions', 'version')
    # ### end Alembic commands ###
