"""baseline: career_sessions table

Revision ID: af2bf91f47dd
Revises: 
Create Date: 2026-08-18 18:34:25.296625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2bf91f47dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('current_season', sa.Integer(), nullable=False),
    sa.Column('pending_event_id', sa.String(length=64), nullable=True),
    sa.Column('pending_event_reason', sa.String(length=500), nullable=True),
    sa.Column('events_resolved_total', sa.Integer(), nullable=False),
    sa.Column('player_data', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('pending_chains', sa.JSON(), nullable=False),
    sa.Column('season_progress', sa.JSON(), nullable=False),
    sa.Column('pending_roulette', sa.JSON(), nullable=True),
    sa.Column('pending_transfer_window', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_sessions')
    # ### end Alembic commands ###
