"""add pending retirement column

Revision ID: b542b5067cf1
Revises: 9621b3f1a976
Create Date: 2026-08-18 23:21:45.228336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b542b5067cf1'
down_revision: Union[str, Sequence[str], None] = '9621b3f1a976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_sessions', sa.Column('pending_retirement', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_sessions', 'pending_retirement')
    # ### end Alembic commands ###
